var express = require('express');
var router = express.Router();
var fs = require('fs');
var upload = multer();
router.get('/', function(req, res){
   console.log('Request recieved / ', __dirname);
   res.sendFile(__dirname + '/upload/126ea9c95066e237825d43b8efb6194d');
   // res.send("Hello world!!!!");
});
/*
router.post('/addProduct', function(req, res){
   console.log('Add Product service call.. ');
   console.log(req);
   res.send("Hello world!!!!");
});
*/

router.post('/addProduct',upload.single('fileData'), (req, res,next) => {
  console.log('calling add product ', req.file);//this will be automatically set by multer
  console.log(req.body);
  //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
  fs.readFile(req.file.path,(err, contents)=> {
   if (err) {
   console.log('Error: ', err);
  }else{
   console.log('File contents ',contents);
   res.send('success');
  }
 });
});

router.all("*", function(req, res) {
    res.status(404).json({success: false}).end();
});

module.exports = router;