var express = require('express');
var router = express.Router();
var fs = require('fs');
var multer = require('multer');
var upload = multer();
var mysql = require('mysql');

var con = mysql.createConnection({
  host: "techserver.techbuiz.com",
  user: "remoteabdullah",
  password: "remoteabbasi",
  database: "techbuiz_mysql"
});

con.connect(function(err) {
  if (err) throw err;
  console.log('MysqL Connected *****');
  con.query("SELECT * FROM customers", function (err, result, fields) {
    if (err) throw err;
    console.log(result);
  });
});

var config = {
  username: 'root',
  password: '#Abby@12345',
  apiKey: 'sBMxRYgJLjQcDN1AbJ7KBUIrDqcT9UFd',
  serverUrl: 'http://techbuiz.com/admin/includes/api.php'
};

router.get('/', function(req, res){
   console.log('Request recieved ping');
   res.send('success');
// res.send("Hello world!!!!");
});

router.get('/getAllProducts', function(req, res){
   console.log('Request recieved get all products');
   var sql = "select * from products;"
    var resultArray  = [];
    con.query(sql, function (err, result, fields) {
      if (err) throw err;
        console.log(result);
        resultArray = Object.values(JSON.parse(JSON.stringify(result)))
          console.log('result ', resultArray);
          res.send(resultArray);
      });

// res.send("Hello world!!!!");
});
/*
router.post('/addProduct', function(req, res){
   console.log('Add Product service call.. ');
   console.log(req);
   res.send("Hello world!!!!");
});
*/

router.post('/addProduct',upload.single('fileData'), (req, res,next) => {
  console.log('calling add product ', req.file);//this will be automatically set by multer
   var fileName ="'" +  __dirname + req.file.filename + "'";
  console.log('fileName', fileName);
  //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
 fs.readFile(req.file.path,(err, contents)=> {
   if (err) {
   console.log('Error: ', err);
  }else{
    var sql = "INSERT INTO products (file_name, name, description, category, brand, price) VALUES ("+ fileName +",'pname','pdesc','pcategaory','pbrand', 'pprice');"
         console.log('File contents ',contents);
        var sqlResult  = '';
        con.query(sql, function (err, result, fields) {
          if (err) throw err;
             sqlResult = result;
              console.log(result);
              res.send(sqlResult);
          });
  }
 });
});


router.all("*", function(req, res) {
    res.status(404).json({success: false}).end();
});


module.exports = router;
